"""add product image url

Revision ID: 386b28b20008
Revises: ed9193f3ddf7
Create Date: 2026-01-10 08:51:31.468968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386b28b20008'
down_revision = 'ed9193f3ddf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
